const docs = [
  {
    "id":"1",
    "name": "G.Chakradhar Reddy",
    "location": "kurnool",
    "rating": "4",
    "specialization": "Psychiartist",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":9,
    "endTime":17,
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5"

    
  },
  {
    "id":"2",
    "name": "B.Sai Vamshi",
    "location": "banglore",
    "specialization": "Psychiartist",
    "rating": "5",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"3",
    "endTime":"7",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  },
  {
    "id":"3",
    "name": "C.Srikar",
    "location": "banglore",
    "specialization": "opthamologist",
    "rating": "3",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"2",
    "endTime":"5",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  },
  {
    "id":"4",
    "name": "A.Meeraj",
    "location": "kurnool",
    "rating": "4",
    "specialization": "cardiaogy",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"9",
    "endTime":"12",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
    
  },
  {
    "id":"5",
    "name": "M.Mounsih",
    "location": "kurnool",
    "specialization": "dentist",
    "rating": "5",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"3",
    "endTime":"7",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  },
  {
    "id":"6",
    "name": "C.Jagan",
    "location": "banglore",
    "specialization": "opthamologist",
    "rating": "3",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"2",
    "endTime":"5",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  },
  {
    "id":"7",
    "name": "K.Kalyan",
    "location": "banglore",
    "specialization": "opthamologist",
    "rating": "3",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"2",
    "endTime":"5",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  },
  {
    "id":"8",
    "name": "E.Uma",
    "location": "banglore",
    "specialization": "opthamologist",
    "rating": "3",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"2",
    "endTime":"5",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  },
  {
    "id":"9",
    "name": "T.Bhanupriya",
    "location": "banglore",
    "specialization": "opthamologist",
    "rating": "3",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"2",
    "endTime":"5",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  },
  {
    "id":"10",
    "name": "Meera",
    "location": "banglore",
    "specialization": "cardiology",
    "rating": "5",
    "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
    "startTime":"2",
    "endTime":"5",
    "address":"Appolo hospitals,gandhi nagar",
    "expe":"5",
  }
  
];
export default docs;