const docs = [
    {
      "id":"1",
      "name": "Shankar Dada MBBS",
      "location": "kurnool",
      "rating": "4",
      "specialization": "cardiaogy",
      "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
      "startTime":9,
      "endTime":12,
      "address":"Appolo hospitals,gandhi nagar",
      "expe":"5",
       "slot1":"9-10",
       "slot2":"10-11",
       "slot3":"11-12",
       "slot4":"12-13",
       "slot5":"15-16",
       "slot6":"16-17",
       "slot7":"17-18",
       "slot8":"19-20",

      
    },
    {
      "id":"2",
      "name": "cde",
      "location": "kurnool",
      "specialization": "dentist",
      "rating": "5",
      "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
      "startTime":"3",
      "endTime":"7",
      "address":"Appolo hospitals,gandhi nagar",
      "expe":"5",
    },
    {
      "id":"3",
      "name": "fgh",
      "location": "banglore",
      "specialization": "opthamologist",
      "rating": "3",
      "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
      "startTime":"2",
      "endTime":"5",
      "address":"Appolo hospitals,gandhi nagar",
      "expe":"5",
    },
    {
      "id":"4",
      "name": "abc",
      "location": "kurnool",
      "rating": "4",
      "specialization": "cardiaogy",
      "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
      "startTime":"9",
      "endTime":"12",
      "address":"Appolo hospitals,gandhi nagar",
      "expe":"5",
      
    },
    {
      "id":"5",
      "name": "cde",
      "location": "kurnool",
      "specialization": "dentist",
      "rating": "5",
      "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
      "startTime":"3",
      "endTime":"7",
      "address":"Appolo hospitals,gandhi nagar",
      "expe":"5",
    },
    {
      "id":"6",
      "name": "fgh",
      "location": "banglore",
      "specialization": "opthamologist",
      "rating": "3",
      "about":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh tellus molestie nunc non blandit massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.",
      "startTime":"2",
      "endTime":"5",
      "address":"Appolo hospitals,gandhi nagar",
      "expe":"5",
    }
    
  ];
  export default docs;
  